apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: dab8106/NAMESPACE_PLACEHOLDER-javaweb:latest
          ports:
            - containerPort: 8080
